/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React from "react";
import { 
  AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer,
  PieChart, Pie, Cell, BarChart, Bar, LineChart, Line
} from "recharts";
import { 
  SlidersHorizontal, Share2, Download, HelpCircle
} from "lucide-react";
import { AnalysisResults } from "../types";

interface AnalyticsDashboardProps {
  results: AnalysisResults;
  question: string;
}

export default function AnalyticsDashboard({ results, question }: AnalyticsDashboardProps) {
  const colors = ["#1e3b8b", "#3b82f6", "#10b981", "#ef4444", "#8b5cf6", "#f59e0b"];

  const getCohortColor = (value: number) => {
    if (value >= 90) return "bg-blue-600/90 text-white";
    if (value >= 80) return "bg-blue-500/80 text-blue-100";
    if (value >= 70) return "bg-indigo-500/70 text-indigo-100";
    if (value >= 65) return "bg-indigo-600/50 text-slate-300";
    if (value >= 60) return "bg-indigo-700/30 text-slate-400";
    return "bg-slate-900 text-slate-500";
  };

  const chartMeta = results?.charts || {};
  const hasCharts = Object.keys(chartMeta).length > 0;

  return (
    <div id="analytics-view" className="space-y-8 text-left">
      {/* Upper header */}
      <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
        <div>
          <span className="text-xs font-mono text-indigo-400 font-bold uppercase tracking-widest">Executive Analytics Node</span>
          <h2 className="font-display font-bold text-2xl text-white mt-1">Analysis Workflow Summary</h2>
          <p className="text-slate-400 text-xs mt-0.5">Target Scope: "{question}"</p>
        </div>

        {/* Global actions */}
        <div className="flex items-center gap-3">
          <button onClick={() => alert("Actions ready")} className="px-3.5 py-1.5 border border-slate-800 hover:bg-slate-900 rounded-lg text-xs font-semibold text-slate-300 flex items-center gap-2">
            <SlidersHorizontal className="w-3.5 h-3.5" /> Options
          </button>
          <button onClick={() => alert("Exported")} className="px-3.5 py-1.5 bg-blue-600 hover:bg-blue-500 text-xs font-semibold text-white rounded-lg flex items-center gap-2 shadow-lg shadow-blue-500/10">
            <Download className="w-3.5 h-3.5" /> Export Data
          </button>
        </div>
      </div>

      {/* Dynamic Summary Cards Grid fallback to object keys */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        {results?.summary && Object.entries(results.summary).map(([key, item]: [string, any]) => (
          <div key={key} className="p-5 rounded-2xl bg-slate-900/40 border border-slate-850">
            <span className="text-xs text-slate-500 font-medium uppercase tracking-wider">{key.replace(/([A-Z])/g, ' $1')}</span>
            <div className="text-3xl font-extrabold text-white mt-1">{item.value ?? item}</div>
            {item.change && (
              <span className="text-xs text-slate-400 font-semibold font-mono mt-1.5 block">
                {item.change} delta variance
              </span>
            )}
          </div>
        ))}
      </div>

      {!hasCharts ? (
        <div className="p-12 border border-dashed border-slate-800 rounded-2xl text-center text-slate-500 font-mono text-sm flex flex-col items-center justify-center gap-2">
          <HelpCircle className="w-5 h-5 text-slate-600" />
          <span>No specific chart configurations generated by visualization models for this dataset slice.</span>
        </div>
      ) : (
        <>
          {/* 2. Dynamic Charts Mapping Block */}
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            {/* 1. Trend Line/Area Parser */}
            {chartMeta.revenueTrend && (
              <div className="p-5 border border-slate-850 bg-slate-950 rounded-2xl space-y-4">
                <div>
                  <h3 className="font-semibold text-white text-sm">Value Vectors Timeline</h3>
                  <p className="text-xs text-slate-500 mt-0.5">Continuous evaluation traces extracted from file records</p>
                </div>
                <div className="h-64">
                  <ResponsiveContainer width="100%" height="100%">
                    <AreaChart data={chartMeta.revenueTrend}>
                      <defs>
                        <linearGradient id="colorDynamicRev" x1="0" y1="0" x2="0" y2="1">
                          <stop offset="5%" stopColor="#3b82f6" stopOpacity={0.2}/>
                          <stop offset="95%" stopColor="#3b82f6" stopOpacity={0}/>
                        </linearGradient>
                      </defs>
                      <CartesianGrid strokeDasharray="3 3" stroke="#0f172a" />
                      <XAxis dataKey="date" stroke="#475569" fontSize={10} tickLine={false} />
                      <YAxis stroke="#475569" fontSize={10} tickLine={false} />
                      <Tooltip contentStyle={{ backgroundColor: "#020617", border: "1px solid #1e293b", color: "#f1f5f9" }} />
                      <Area type="monotone" dataKey="value" stroke="#3b82f6" strokeWidth={2} fillOpacity={1} fill="url(#colorDynamicRev)" />
                    </AreaChart>
                  </ResponsiveContainer>
                </div>
              </div>
            )}

            {/* 2. Categorical Distribution / Mix Map */}
            {chartMeta.revenueSegment && (
              <div className="p-5 border border-slate-850 bg-slate-950 rounded-2xl space-y-4">
                <div>
                  <h3 className="font-semibold text-white text-sm">Parameters Share Mix</h3>
                  <p className="text-xs text-slate-500 mt-0.5">Proportional tracking metrics allocation</p>
                </div>
                <div className="h-64 flex flex-col justify-between">
                  <div className="h-48 relative">
                    <ResponsiveContainer width="100%" height="100%">
                      <PieChart>
                        <Pie
                          data={chartMeta.revenueSegment}
                          cx="50%"
                          cy="50%"
                          innerRadius={60}
                          outerRadius={80}
                          paddingAngle={5}
                          dataKey="value"
                        >
                          {chartMeta.revenueSegment.map((entry: any, index: number) => (
                            <Cell key={`cell-${index}`} fill={colors[index % colors.length]} />
                          ))}
                        </Pie>
                        <Tooltip />
                      </PieChart>
                    </ResponsiveContainer>
                  </div>
                  <div className="flex flex-wrap justify-center gap-4 text-xs">
                    {chartMeta.revenueSegment.map((item: any, idx: number) => (
                      <div key={item.name} className="flex items-center gap-1.5">
                        <span className="w-2.5 h-2.5 rounded-full" style={{ backgroundColor: colors[idx % colors.length] }} />
                        <span className="text-slate-400">{item.name}: {item.value}</span>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            )}

            {/* 3. High Volume Regional/Bar Matrix */}
            {chartMeta.revenueRegion && (
              <div className="p-5 border border-slate-850 bg-slate-950 rounded-2xl space-y-4 lg:col-span-2">
                <div>
                  <h3 className="font-semibold text-white text-sm">Categorical Aggregations Comparison</h3>
                </div>
                <div className="h-56">
                  <ResponsiveContainer width="100%" height="100%">
                    <BarChart data={chartMeta.revenueRegion}>
                      <CartesianGrid strokeDasharray="3 3" stroke="#0f172a" vertical={false} />
                      <XAxis dataKey="region" stroke="#475569" fontSize={10} tickLine={false} />
                      <YAxis stroke="#475569" fontSize={10} tickLine={false} />
                      <Tooltip />
                      <Bar dataKey="value" fill="#3b82f6" radius={[4, 4, 0, 0]} />
                    </BarChart>
                  </ResponsiveContainer>
                </div>
              </div>
            )}
          </div>

          {/* 3. Heatmaps and Secondary Multi-variate calculations blocks conditional check */}
          {chartMeta.cohortRetention && (
            <div className="p-5 border border-slate-850 bg-slate-950 rounded-2xl space-y-4">
              <div>
                <h3 className="font-semibold text-white text-sm">Dynamic Cohort Retention Matrix</h3>
                <p className="text-xs text-slate-500 mt-0.5">Extracted cohort longevity retention metrics percentages</p>
              </div>
              <div className="space-y-1.5">
                {chartMeta.cohortRetention.map((cohort: any, idx: number) => {
                  const weeksData = Object.entries(cohort).filter(([k]) => k.startsWith("week")).map(([, v]) => v as number);
                  return (
                    <div key={idx} className="flex items-center gap-1 text-[10px]">
                      <span className="w-16 truncate font-mono text-slate-500">{cohort.cohort || `Group ${idx + 1}`}</span>
                      <div className="flex-1 grid grid-cols-12 gap-[2px]">
                        {weeksData.map((val, wIdx) => (
                          <div 
                            key={wIdx} 
                            className={`h-4 text-[8px] font-mono rounded-[2px] flex items-center justify-center font-medium ${getCohortColor(val)}`}
                            title={`Interval ${wIdx + 1}: ${val}%`}
                          >
                            {val}
                          </div>
                        ))}
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          )}

          {/* 4. Forecast Section */}
          {chartMeta.forecast && (
            <div className="p-5 border border-slate-850 bg-slate-950 rounded-2xl space-y-4">
              <div>
                <h3 className="font-semibold text-white text-sm">Predictive Modeling Forecast Node</h3>
                <p className="text-xs text-slate-500 mt-0.5">Point estimates mapped from chronological metrics array</p>
              </div>
              <div className="h-48">
                <ResponsiveContainer width="100%" height="100%">
                  <LineChart data={chartMeta.forecast}>
                    <CartesianGrid strokeDasharray="3 3" stroke="#0f172a" />
                    <XAxis dataKey="month" stroke="#475569" fontSize={10} tickLine={false} />
                    <YAxis stroke="#475569" fontSize={10} tickLine={false} />
                    <Tooltip />
                    <Line type="monotone" dataKey="actual" stroke="#3b82f6" strokeWidth={2.5} name="Historical" dot={{ r: 3 }} />
                    <Line type="monotone" dataKey="forecast" stroke="#10b981" strokeWidth={2} strokeDasharray="4 4" name="Projected Model" />
                  </LineChart>
                </ResponsiveContainer>
              </div>
            </div>
          )}
        </>
      )}
    </div>
  );
}